### ISSUE TITLE
scikit-tda installation error (help)

### ISSUE THREAD

**Issue by henry0244** [scikit-tda/scikit-tda#10]
I tried installing this package on jupiter notes but had an error. could someone suggest a solution to me? find below the result after entering 

pip install sckit_tda

Collecting scikit-tda
  Using cached https://files.pythonhosted.org/packages/e2/67/14676df9d3c8fae3324f6a73e60e9b705c1dfea8131e275a313ab90bd09d/scikit_tda-0.0.3-py3-none-any.whl
Requirement already satisfied: scipy in c:\users\user\anaconda3\lib\site-packages (from scikit-tda) (1.2.1)
Requirement already satisfied: scikit-learn in c:\users\user\anaconda3\lib\site-packages (from scikit-tda) (0.21.2)
Requirement already satisfied: Cython in c:\users\user\anaconda3\lib\site-packages (from scikit-tda) (0.29.12)
Requirement already satisfied: pillow in c:\users\user\anaconda3\lib\site-packages (from scikit-tda) (6.1.0)
Requirement already satisfied: umap-learn in c:\users\user\anaconda3\lib\site-packages (from scikit-tda) (0.3.10)
Requirement already satisfied: matplotlib in c:\users\user\anaconda3\lib\site-packages (from scikit-tda) (3.1.0)
Requirement already satisfied: persim in c:\users\user\anaconda3\lib\site-packages (from scikit-tda) (0.1.1)
Requirement already satisfied: numba in c:\users\user\anaconda3\lib\site-packages (from scikit-tda) (0.44.1)
Requirement already satisfied: kmapper in c:\users\user\anaconda3\lib\site-packages (from scikit-tda) (1.2.0)
Requirement already satisfied: tadasets in c:\users\user\anaconda3\lib\site-packages (from scikit-tda) (0.0.4)
Collecting ripser (from scikit-tda)
  Using cached https://files.pythonhosted.org/packages/4c/17/d5e898161eb8e3b1084419bfc04adbe87d15075daa8e236df72dbe75167e/ripser-0.4.1.tar.gz
Requirement already satisfied: numpy in c:\users\user\anaconda3\lib\site-packages (from scikit-tda) (1.16.4)
Requirement already satisfied: joblib>=0.11 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn->scikit-tda) (0.13.2)
Requirement already satisfied: cycler>=0.10 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->scikit-tda) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->scikit-tda) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->scikit-tda) (2.4.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->scikit-tda) (2.8.0)
Requirement already satisfied: hopcroftkarp in c:\users\user\anaconda3\lib\site-packages (from persim->scikit-tda) (1.2.5)
Requirement already satisfied: llvmlite>=0.29.0 in c:\users\user\anaconda3\lib\site-packages (from numba->scikit-tda) (0.29.0)
Requirement already satisfied: Jinja2 in c:\users\user\anaconda3\lib\site-packages (from kmapper->scikit-tda) (2.10.1)
Requirement already satisfied: six in c:\users\user\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib->scikit-tda) (1.12.0)
Requirement already satisfied: setuptools in c:\users\user\anaconda3\lib\site-packages (from kiwisolver>=1.0.1->matplotlib->scikit-tda) (41.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\user\anaconda3\lib\site-packages (from Jinja2->kmapper->scikit-tda) (1.1.1)
Building wheels for collected packages: ripser
  Building wheel for ripser (setup.py): started
  Building wheel for ripser (setup.py): finished with status 'error'
  Running setup.py clean for ripser
Failed to build ripser
Installing collected packages: ripser, scikit-tda
  Running setup.py install for ripser: started
    Running setup.py install for ripser: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.
  ERROR: Complete output from command 'C:\Users\USER\Anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-gkx47tif\\ripser\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\USER\AppData\Local\Temp\pip-wheel-g8wqt8pm' --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\ripser
  copying ripser\ripser.py -> build\lib.win-amd64-3.7\ripser
  copying ripser\_version.py -> build\lib.win-amd64-3.7\ripser
  copying ripser\__init__.py -> build\lib.win-amd64-3.7\ripser
  running build_ext
  building 'pyRipser' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for ripser
    ERROR: Complete output from command 'C:\Users\USER\Anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-gkx47tif\\ripser\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\USER\AppData\Local\Temp\pip-record-3xthkebx\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\ripser
    copying ripser\ripser.py -> build\lib.win-amd64-3.7\ripser
    copying ripser\_version.py -> build\lib.win-amd64-3.7\ripser
    copying ripser\__init__.py -> build\lib.win-amd64-3.7\ripser
    running build_ext
    building 'pyRipser' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command "'C:\Users\USER\Anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-gkx47tif\\ripser\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\USER\AppData\Local\Temp\pip-record-3xthkebx\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\USER\AppData\Local\Temp\pip-install-gkx47tif\ripser\

**Comment by ctralie** [comment]
Yes, you will need to download the free version of Microsoft Visual Studio:
https://visualstudio.microsoft.com/downloads/

**Comment by catanzaromj** [comment]
Closing as out of date.
