### ISSUE TITLE
Can you provide some images generated by this tool？

### ISSUE THREAD

**Issue by 23df** [scikit-tda/scikit-tda#12]
As the Google Image search for "topological data analysis" shows.
Thanks!

**Comment by ctralie** [comment]
It sounds like you might be interested in our notebooks:

https://github.com/scikit-tda/ripser.py/tree/master/docs/notebooks

Best,
Chris

**Comment by catanzaromj** [comment]
@23df You should check out the main tutorial [here in the docs](https://docs.scikit-tda.org/en/latest/notebooks/scikit-tda%20Tutorial.html), as well as the tutorials in the individual package's documentation.
