### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by rpanai** [scikit-tda/scikit-tda#13]
Hi, I was trying to add this package to conda-forge but I just realize there is no license file in this repo. Do you mind to add one? It looks to me you could add something like [this](https://github.com/facebookresearch/hiplot/blob/master/LICENSE) if you want a MIT license

**Comment by ctralie** [comment]
Interesting.  We have ripser.py and other modules under the MIT license
already, but I didn't realize we were lacking this at the parent level.
@sauln, could you handle this one?

**Comment by bdice** [comment]
@rpanai Let me know if you need any help with conda-forge. I helped @sauln set up the conda-forge packages for ripser.py and persim last summer at SciPy 2019 sprints. 👍

**Comment by rpanai** [comment]
@bdice Thank you. Yesterday I watched the talk and I saw about the sprints. I already added few packages to conda-forge but if i'll need any help I'll ask you for sure. Thank you.

**Comment by sauln** [comment]
By all means, add the license file. I'll keep my eyes out for the PR.

**Comment by sauln** [comment]
Though, @rpanai, this repo doesn't provide any more functionality than the other packages it imports. It mostly houses documentation for the project and aggregates the various projects.  I'm not sure anyone is actually using it directly.  

It'll probably be forever on the todo list, but it would be nice to give this repo some more life by better organizing and exposing the various functionality from the other projects.  If you'd like to contribute in other ways after the conda-forge stuff, let me know!
