### ISSUE TITLE
A "Getting Started" section of the documentation would be helpful.

### ISSUE THREAD

**Issue by galenseilis** [scikit-tda/scikit-tda#23]
In addition to the [promised tutorials](https://scikit-tda.org/tutorials/index.html) for this software package, a short "Getting Started" section would help me understand how to use this software package.

**Comment by 23pointsNorth** [comment]
Agreed, the initial curve is larger. I think the main github README + that docs section should have at least something basic like 

```
import tadasets
import matplotlib.pyplot as plt
data_clean = tadasets.dsphere(d=1, n=100, noise=0.0)
data_noisy = tadasets.dsphere(d=1, n=100, noise=0.1)


print(f"The shape of the data is: {data_clean.shape}")

plt.scatter(data_clean[:,0], data_clean[:,1], label="clean data")
plt.scatter(data_noisy[:,0], data_noisy[:,1], label="noisy data")
plt.axis('equal')
plt.legend()
plt.show()


# Let's calculate the diagram 
import ripser
from persim import plot_diagrams

dgm_clean = ripser.ripser(data_clean)['dgms'][1]
dgm_noisy = ripser.ripser(data_noisy)['dgms'][1]

plot_diagrams([dgm_clean, dgm_noisy] , labels=['Clean $H_1$', 'Noisy $H_1$'], show=True)
```

**Comment by catanzaromj** [comment]
@galenseilis @23pointsNorth Please see the [Tutorial section](https://scikit-tda.readthedocs.io/en/latest/notebooks/scikit-tda%20Tutorial.html) of the docs. Hopefully this will address some of your concerns.

**Comment by catanzaromj** [comment]
@galenseilis @23pointsNorth If you have suggestions for more broad tutorials that could be added here, please open an issue and we can address it. You can submit a PR as well if you'd like. Also please open issues/PRs on the other scikit-tda modules if you find their examples lacking as well. Thanks!
