### ISSUE TITLE
Website appears to be down [BUG]

### ISSUE THREAD

**Issue by tedtroxell** [scikit-tda/scikit-tda#32]
I'm looking to view your documentation on your website scikit-tda.org and the site appears to be down. I've tried multiple browsers, computers and ip addresses, but no luck.

**Comment by tedtroxell** [comment]
I was able to find the documentation here -> https://docs.scikit-tda.org/en/latest/ perhaps just updating the github repo to point to the subdomains would be better in the future

**Comment by catanzaromj** [comment]
@tedtroxell Thanks for the reminder about this! We've been having some issues with the domain, but we will update the links to the docs.scikit-tda.org link as you mention.
